'use strict';

(function () {

    const $ = id => document.getElementById(id);

    // ---------- Presets ----------
    // 每個 preset 一個句子 + 「signal」設定：告訴 head-builder 哪個詞應該
    // 特別關注哪個詞。剩下的隨機/位置填充。
    // signals[headIdx] = [{from, to, weight}, ...]
    //   from = query 詞 idx，to = key 詞 idx，weight = raw pre-softmax 分數
    //   高分（4-6）→ softmax 後接近 60-80% 注意力；低分（0-1）分散
    const PRESETS = [
        {
            id: 'zh-pronoun',
            label: '🇹🇼「它」到底指誰？（中文代詞解析）',
            tokens: ['我', '今天', '買了', '一本', '書', '晚上', '開始', '讀', '它'],
            noteLines: [
                '典型的中文代詞指代例句：<b>「我今天買了一本書，晚上開始讀它」</b>（原論文用的是英文 "The animal didn\'t cross the street because it was too tired"，見 en-transformer-original preset）。',
                '中間隔了 4 個詞才出現的「它」，人類一看就知道指「書」。',
                '<b>RNN</b>：訊息一步一步傳，遠距離的「書 → 它」很容易忘掉。',
                '<b>Attention</b>：「它」直接一步關注到「書」，距離不再是問題。',
                '👆 點「它」看 Head 1「代詞解析」的箭頭精準指向「書」。',
                '⚠️ 為了視覺清爽，token 陣列省略了逗號跟句號（真實 tokenizer 會保留）。',
            ],
            signals: {
                0: [   // Head 1 代詞解析: pronoun → antecedent noun
                    { from: 8, to: 4, weight: 6.0 },  // 它→書 超強
                    { from: 8, to: 7, weight: 2.5 },  // 它→讀 中
                ],
                1: [   // Head 2 主語追蹤: verb → subject
                    { from: 2, to: 0, weight: 5.0 },  // 買了→我
                    { from: 6, to: 0, weight: 3.5 },  // 開始→我
                    { from: 7, to: 0, weight: 4.5 },  // 讀→我
                ],
                2: [   // Head 3 動作對象: verb → object
                    { from: 2, to: 4, weight: 5.0 },  // 買了→書
                    { from: 7, to: 8, weight: 4.5 },  // 讀→它
                ],
                3: [   // Head 4 時間關係
                    { from: 5, to: 1, weight: 4.5 },  // 晚上→今天
                    { from: 1, to: 5, weight: 3.0 },
                ],
                4: [   // Head 5 相鄰 bigram
                    // Generated by rule (below), no explicit signals
                ],
                5: [   // Head 6 全局散播 (nothing special)
                ],
                6: [   // Head 7 修飾關係
                    { from: 3, to: 4, weight: 5.0 },  // 一本→書
                    { from: 4, to: 3, weight: 3.5 },
                ],
                7: [   // Head 8 反向照應 (書→它)
                    { from: 4, to: 8, weight: 4.5 },
                ],
            },
            // 慢動作動畫用的教學文案。key = token idx，value = 短句（≤ 20 字）。
            // 空的自動 fallback：qLabels 用「我這個詞想關注誰」、kLabels 用「我是：<token>」、
            // vLabels 用 token 本身。填得越好動畫教學效果越強——這是給人類編輯的欄位。
            qLabels: {
                8: '我想知道我這個代詞指的是什麼',   // 它
                2: '我想知道我這個動作作用在誰身上', // 買了
                7: '我想知道我這個動作作用在誰身上', // 讀
            },
            kLabels: {
                0: '人稱代詞：我（第一人稱主體）',
                4: '名詞：一種能被買、被讀的實體物品',
                8: '代詞：等待被指涉的物件',
                2: '動詞：購買動作',
                7: '動詞：閱讀動作',
                1: '時間名詞：今天',
                5: '時間名詞：晚上',
            },
            vLabels: {
                0: '第一人稱主體',
                4: '成冊的著作',
                7: '閱讀動作',
                8: '被指涉的物件',
            },
        },
        {
            id: 'en-pronoun',
            label: '🇺🇸 "it" refers to what? (English pronoun)',
            tokens: ['The', 'cat', 'sat', 'on', 'the', 'mat', 'because', 'it', 'was', 'tired'],
            noteLines: [
                'Classic ambiguous English: <b>"The cat sat on the mat because it was tired."</b>',
                '"it" could refer to "cat" or "mat" grammatically. Semantic clues (cats get tired, mats don\'t) point to "cat".',
                'A well-trained Transformer picks up this via <b>Head 1</b>: pronoun → antecedent with semantic match.',
                '👆 Click "it" and see the arrow point to "cat", not "mat".',
            ],
            signals: {
                0: [ { from: 7, to: 1, weight: 5.5 }, { from: 7, to: 5, weight: 1.0 } ],
                1: [ { from: 8, to: 1, weight: 5.0 }, { from: 2, to: 1, weight: 4.5 }, { from: 9, to: 1, weight: 4.0 } ],
                2: [ { from: 2, to: 5, weight: 3.5 }, { from: 3, to: 5, weight: 4.0 } ],
                3: [ { from: 6, to: 2, weight: 3.5 } ],   // because → sat
                4: [],
                5: [],
                6: [ { from: 0, to: 1, weight: 4.0 }, { from: 4, to: 5, weight: 4.0 } ],  // The→cat, the→mat
                7: [ { from: 1, to: 7, weight: 3.5 } ],   // cat ↔ it
            },
            qLabels: {
                7: 'I want to know what noun I refer to',   // it
            },
            kLabels: {
                1: 'noun: cat (an animate creature)',
                5: 'noun: mat (an inanimate object)',
                7: 'pronoun: awaiting antecedent',
            },
            vLabels: {
                1: 'the cat (subject)',
                5: 'the mat (location)',
            },
        },
        {
            id: 'zh-sentiment',
            label: '🍜「但是」翻轉情緒（餐廳評論）',
            tokens: ['這家', '餐廳', '服務', '很', '差', '但是', '菜', '真的', '好吃'],
            noteLines: [
                '評論句：<b>「這家餐廳服務很差，但是菜真的好吃」</b>',
                '模型要抓的是<b>「但是」</b>這個轉折——它切開情感兩半，讓「差」跟「好吃」不會混。',
                '<b>Head 4</b>「邏輯關係」抓「但是→差」跟「但是→好吃」都很強，這樣模型知道兩邊是對比的。',
                '<b>Head 8</b>「反向照應」讓「好吃」回頭看「菜」，「差」回頭看「服務」，情感歸屬正確。',
                '👆 點「但是」看它同時關注兩個對立情感詞。',
                '⚠️ token 陣列省略了原句的逗號（真實 tokenizer 保留）。',
            ],
            signals: {
                0: [],
                1: [ { from: 4, to: 2, weight: 4.5 }, { from: 8, to: 6, weight: 4.5 } ],   // 差→服務、好吃→菜
                2: [],
                3: [ { from: 5, to: 4, weight: 4.0 }, { from: 5, to: 8, weight: 4.0 } ],   // 但是關注兩邊
                4: [],
                5: [],
                6: [ { from: 3, to: 4, weight: 4.0 }, { from: 7, to: 8, weight: 4.0 } ],   // 很→差、真的→好吃
                7: [ { from: 8, to: 6, weight: 4.5 }, { from: 4, to: 2, weight: 4.5 } ],
            },
            qLabels: {
                5: '我這個轉折詞想同時關注兩個對立情感',   // 但是
            },
            kLabels: {
                4: '情感詞：負面（差）',
                8: '情感詞：正面（好吃）',
                2: '名詞：服務',
                6: '名詞：菜',
                5: '邏輯連詞：轉折',
            },
            vLabels: {
                4: '負面情感內容',
                8: '正面情感內容',
                2: '評論對象：服務品質',
                6: '評論對象：食物',
            },
        },
        {
            id: 'en-transformer-original',
            label: '📄 原論文示範例句：animal / street / it 的歧義',
            tokens: ['The', 'animal', "didn't", 'cross', 'the', 'street', 'because', 'it', 'was', 'too', 'tired'],
            noteLines: [
                '<b>「Attention Is All You Need」原論文</b>展示 Transformer 注意力視覺化時用的經典句：<b>"The animal didn\'t cross the street because it was too tired."</b>',
                '"it" 語法上可以指 <b>animal</b> 或 <b>street</b>——只有語意能區分（動物會累、街道不會）。',
                'BERT / GPT 等真實模型都能學到 "it → animal"，但這個是<b>語意推理</b>不是純語法。',
                '👆 點 "it" 看 Head 1「代詞解析」正確指向 animal 而非 street。',
                '換 "tired" → "wide" 變成 "The animal didn\'t cross the street because it was too wide"，這時 it 應該指 street（街太寬）——這正是原論文 Figure 4 展示的多頭差異。',
            ],
            signals: {
                0: [   // Head 1 代詞解析
                    { from: 7, to: 1, weight: 6.0 },  // it → animal (semantic winner)
                    { from: 7, to: 5, weight: 1.5 },  // it → street (weaker, semantic loser)
                ],
                1: [   // Head 2 主語追蹤
                    { from: 8, to: 1, weight: 5.0 },  // was → animal
                    { from: 3, to: 1, weight: 4.5 },  // cross → animal
                ],
                2: [   // Head 3 動作對象
                    { from: 3, to: 5, weight: 5.0 },  // cross → street
                ],
                3: [   // Head 4 邏輯關係
                    { from: 6, to: 3, weight: 4.0 },  // because → cross
                    { from: 6, to: 9, weight: 3.5 },  // because → too
                ],
                4: [],
                5: [],
                6: [   // Head 7 修飾關係
                    { from: 0, to: 1, weight: 4.5 },  // The → animal
                    { from: 4, to: 5, weight: 4.5 },  // the → street
                    { from: 9, to: 10, weight: 4.0 }, // too → tired
                ],
                7: [   // Head 8 (待改 hint)
                    { from: 10, to: 1, weight: 3.5 },  // tired → animal (adj → noun it describes)
                ],
            },
            qLabels: {
                7: 'What noun do I refer to? (animate or inanimate?)',
            },
            kLabels: {
                1: 'noun: animal (can get tired)',
                5: 'noun: street (cannot get tired)',
                7: 'pronoun: ambiguous reference',
                10: 'adjective: tired (an animate trait)',
            },
            vLabels: {
                1: 'the animal (subject who is tired)',
                5: 'the street (location)',
            },
        },
        {
            id: 'zh-longrange',
            label: '🏃 遠距離依賴（Attention 的殺手鐧）',
            tokens: ['雖然', '天氣', '很', '冷', '但是', '我', '還是', '穿', '短袖', '出門'],
            noteLines: [
                '<b>「雖然...但是...」</b>是遠距離依賴的教科書例子。中間 5-6 個詞後，「但是」還要能想起「雖然」。',
                'RNN 的記憶會被中間的詞稀釋掉。Attention 一步直達。',
                '<b>Head 1</b> 抓「但是→雖然」的邏輯配對，展現 Transformer 對長距離的優勢。',
                '同時「短袖」跟「冷」是矛盾對比，「穿→短袖」是動作對象——多個 head 同時解讀。',
                '👆 點「但是」看 Head 1 精準跨越 4 個詞指向「雖然」。',
                '⚠️ 原句「雖然天氣很冷，但是我還是穿短袖出門」有一個逗號、一個句號，token 陣列為視覺清爽省略。真實 tokenizer 會保留標點作為獨立 token。',
            ],
            signals: {
                0: [ { from: 4, to: 0, weight: 5.5 } ],   // 但是→雖然（遠距離！）
                1: [ { from: 7, to: 5, weight: 5.0 }, { from: 9, to: 5, weight: 4.0 } ],
                2: [ { from: 7, to: 8, weight: 5.0 } ],   // 穿→短袖
                3: [],
                4: [],
                5: [],
                6: [ { from: 2, to: 3, weight: 4.0 } ],  // 很→冷
                7: [ { from: 8, to: 3, weight: 3.5 } ],   // 短袖回頭看冷（矛盾對照）
            },
            qLabels: {
                4: '我這個轉折詞想連回我對應的「雖然」',   // 但是
                7: '我這個動作作用在誰身上',              // 穿
            },
            kLabels: {
                0: '邏輯連詞：讓步（雖然）',
                4: '邏輯連詞：轉折（但是）',
                3: '形容詞：冷',
                8: '名詞：短袖（薄衣）',
            },
            vLabels: {
                0: '讓步子句的內容鋪墊',
                4: '轉折後的核心行動',
                8: '違反直覺的動作對象',
            },
        },
    ];

    const HEAD_META = [
        { name: 'Head 1 · 代詞解析', hint: '代詞跳到它指的名詞', style: 'pronoun' },
        { name: 'Head 2 · 主語追蹤', hint: '動詞找回句子的主語', style: 'subject' },
        { name: 'Head 3 · 動作對象', hint: '動詞連到它作用的對象', style: 'object' },
        { name: 'Head 4 · 邏輯關係', hint: '轉折/因果/時序連詞', style: 'logic' },
        { name: 'Head 5 · 相鄰依賴', hint: '看隔壁的詞（bigram）', style: 'bigram' },
        { name: 'Head 6 · 全局散播', hint: '注意力均勻分散全句', style: 'global' },
        { name: 'Head 7 · 修飾關係', hint: '形容詞/量詞跳到被修飾的詞', style: 'modifier' },
        { name: 'Head 8 · 反向照應', hint: '罕見但真實：先行詞 / 主體回頭看指涉它的詞。BERT 雙向自注意力才有這種對稱', style: 'backref' },
    ];

    // ---------- Matrix builder ----------
    // 每個 head 用「signals + style 的基礎分佈」建 raw score，最後 row-softmax
    function buildMatrix(preset, headIdx) {
        const n = preset.tokens.length;
        const style = HEAD_META[headIdx].style;
        const raw = Array.from({ length: n }, () => new Array(n).fill(0));

        // Baseline: 每個 head 的預設分佈風格
        for (let i = 0; i < n; i++) {
            for (let j = 0; j < n; j++) {
                raw[i][j] = baselineForStyle(style, i, j, n);
            }
        }
        // 疊加 signals
        const signals = (preset.signals[headIdx] || []);
        for (const s of signals) {
            if (s.from < n && s.to < n) {
                raw[s.from][s.to] += s.weight;
            }
        }
        // Row softmax
        const mat = Array.from({ length: n }, () => new Array(n).fill(0));
        for (let i = 0; i < n; i++) {
            const rowMax = Math.max(...raw[i]);
            const exp = raw[i].map(v => Math.exp(v - rowMax));
            const sum = exp.reduce((s, v) => s + v, 0);
            for (let j = 0; j < n; j++) mat[i][j] = exp[j] / sum;
        }
        return { raw, mat };
    }

    function baselineForStyle(style, i, j, n) {
        // seeded pseudo-random so 同一 head 每次載入都一樣
        const seedNoise = ((i * 31 + j * 17 + style.length) % 100) / 100 * 0.4;
        switch (style) {
            case 'pronoun':
            case 'subject':
            case 'object':
            case 'modifier':
                // 淡淡的自關注 + 距離衰減，讓沒 signal 的 row 不至於全零
                return (i === j ? 1.5 : 0) + Math.max(0, 1.5 - Math.abs(i - j) * 0.4) + seedNoise;
            case 'logic':
                return (i === j ? 1.0 : 0) + seedNoise;
            case 'bigram':
                // 只看左右鄰居
                if (Math.abs(i - j) === 1) return 3.0 + seedNoise;
                if (i === j) return 1.5;
                return -0.5 + seedNoise;
            case 'global':
                // 均勻散播
                return 1.0 + seedNoise * 0.5;
            case 'backref':
                // 看反方向（右邊）
                if (j > i && j - i <= 3) return 2.0 + seedNoise;
                if (i === j) return 1.0;
                return seedNoise;
        }
        return seedNoise;
    }

    // ---------- Utils ----------
    function pctStr(v) { return (v * 100).toFixed(1) + '%'; }

    // 依權重取色（顏色越深表示注意力越強）
    function attentionColor(w, alpha = 1) {
        const t = Math.min(1, Math.max(0, w));
        // 白 → 紫
        const r = Math.round(255 - t * (255 - 108));
        const g = Math.round(255 - t * (255 - 40));
        const b = Math.round(255 - t * (255 - 175));
        return `rgba(${r},${g},${b},${alpha})`;
    }

    // ---------- Scene canvas: sentence + arrows ----------
    class SceneChart {
        constructor(canvas) {
            this.canvas = canvas;
            this.ctx = canvas.getContext('2d');
            this.setupHiDPI();
            this.selectedIdx = null;
            this.tokenBounds = [];
            canvas.addEventListener('click', e => this._onClick(e));
        }
        setupHiDPI() {
            const dpr = window.devicePixelRatio || 1;
            const w = this.canvas.clientWidth || this.canvas.width;
            const h = this.canvas.clientHeight || this.canvas.height;
            this.canvas.width = w * dpr;
            this.canvas.height = h * dpr;
            this.ctx.scale(dpr, dpr);
            this.w = w; this.h = h;
        }
        _onClick(e) {
            const rect = this.canvas.getBoundingClientRect();
            const x = (e.clientX - rect.left);
            const y = (e.clientY - rect.top);
            for (const t of this.tokenBounds) {
                if (x >= t.x - t.w / 2 && x <= t.x + t.w / 2 && y >= t.y - 25 && y <= t.y + 25) {
                    this.selectedIdx = t.idx;
                    if (this.onSelect) this.onSelect(t.idx);
                    return;
                }
            }
        }
        setIntensity(v) { this.intensity = v; }
        render(preset, mat, headIdx) {
            const { ctx, w, h } = this;
            ctx.clearRect(0, 0, w, h);
            const tokens = preset.tokens;
            const n = tokens.length;
            const padX = 30, padY = 60;
            const spacing = (w - padX * 2) / (n - 1 || 1);
            // Token 定位在畫面上 30%（Reviewer round 4）：canvas 從 240 拉到 340 後
            // 若 y = h/2 會下移 50px 導致 Stage 2 的 raw 長條圖跟 token 節點重疊。
            // 定 y ≈ h * 0.30 讓：上方留空間給箭頭 + Q 泡泡、下方留 240px 給 Stage 2 三層
            const y = Math.round(h * 0.30);

            // Compute token bounds
            this.tokenBounds = tokens.map((t, i) => {
                const x = padX + i * spacing;
                ctx.font = 'bold 18px -apple-system, "Segoe UI", sans-serif';
                const tw = Math.max(46, ctx.measureText(t).width + 20);
                return { idx: i, x, y, w: tw, text: t };
            });

            // Draw arrows from selected token (before drawing tokens so tokens overlay)
            if (this.selectedIdx !== null && mat) {
                const i = this.selectedIdx;
                const row = mat[i];
                const intensity = this.intensity || 1.5;
                for (let j = 0; j < n; j++) {
                    if (j === i) continue;
                    const w0 = row[j];
                    if (w0 < 0.03) continue;   // 太細跳過
                    const from = this.tokenBounds[i];
                    const to = this.tokenBounds[j];
                    this._drawArrow(from, to, w0 * intensity, w0);
                }
            }

            // Draw tokens
            for (const tb of this.tokenBounds) {
                const isSel = tb.idx === this.selectedIdx;
                ctx.fillStyle = isSel ? '#fef3c7' : '#f3e8ff';
                ctx.strokeStyle = isSel ? '#eab308' : '#a78bfa';
                ctx.lineWidth = isSel ? 3 : 1.5;
                const rx = tb.x - tb.w / 2, ry = tb.y - 22;
                this._roundRect(rx, ry, tb.w, 44, 10);
                ctx.fill();
                ctx.stroke();
                ctx.fillStyle = '#1f2937';
                ctx.font = isSel ? 'bold 18px -apple-system, "Segoe UI", sans-serif' : '18px -apple-system, "Segoe UI", sans-serif';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'middle';
                ctx.fillText(tb.text, tb.x, tb.y);
                // idx label below
                ctx.font = '10px ui-monospace, monospace';
                ctx.fillStyle = '#9ca3af';
                ctx.fillText('#' + tb.idx, tb.x, tb.y + 30);
            }

            // Instruction
            if (this.selectedIdx === null) {
                ctx.fillStyle = '#9ca3af';
                ctx.font = '13px -apple-system, sans-serif';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'top';
                ctx.fillText('👆 點任一個詞看它的注意力扇向哪裡', w / 2, 10);
            } else {
                const t = tokens[this.selectedIdx];
                ctx.fillStyle = '#7c3aed';
                ctx.font = 'bold 13px -apple-system, sans-serif';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'top';
                ctx.fillText(`"${t}" 在 ${HEAD_META[headIdx].name} 下的注意力去向：`, w / 2, 10);
            }
        }
        _drawArrow(from, to, thickness, weight) {
            const ctx = this.ctx;
            const dir = to.x > from.x ? 1 : -1;
            const arch = 40 + Math.abs(to.idx - from.idx) * 10;
            const cx = (from.x + to.x) / 2;
            const cy = from.y - arch;
            // Curve
            ctx.strokeStyle = attentionColor(weight, 0.8);
            ctx.lineWidth = Math.max(0.6, thickness * 6);
            ctx.lineCap = 'round';
            ctx.beginPath();
            ctx.moveTo(from.x, from.y - 22);
            ctx.quadraticCurveTo(cx, cy, to.x, to.y - 22);
            ctx.stroke();
            // Arrow head
            const hx = to.x, hy = to.y - 22;
            const angle = Math.atan2(hy - cy, hx - cx);
            const ah = 8;
            ctx.fillStyle = attentionColor(weight, 0.9);
            ctx.beginPath();
            ctx.moveTo(hx, hy);
            ctx.lineTo(hx - ah * Math.cos(angle - Math.PI / 6), hy - ah * Math.sin(angle - Math.PI / 6));
            ctx.lineTo(hx - ah * Math.cos(angle + Math.PI / 6), hy - ah * Math.sin(angle + Math.PI / 6));
            ctx.closePath();
            ctx.fill();
            // Weight label near mid
            ctx.fillStyle = '#7c3aed';
            ctx.font = 'bold 10px ui-monospace, monospace';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'bottom';
            if (weight >= 0.15) ctx.fillText(pctStr(weight), cx, cy + 6);
        }
        _roundRect(x, y, w, h, r) {
            const ctx = this.ctx;
            ctx.beginPath();
            ctx.moveTo(x + r, y);
            ctx.arcTo(x + w, y, x + w, y + h, r);
            ctx.arcTo(x + w, y + h, x, y + h, r);
            ctx.arcTo(x, y + h, x, y, r);
            ctx.arcTo(x, y, x + w, y, r);
            ctx.closePath();
        }
    }

    // ---------- Matrix heatmap canvas ----------
    class MatrixChart {
        constructor(canvas) {
            this.canvas = canvas;
            this.ctx = canvas.getContext('2d');
            const dpr = window.devicePixelRatio || 1;
            const w = canvas.clientWidth || canvas.width;
            const h = canvas.clientHeight || canvas.height;
            canvas.width = w * dpr;
            canvas.height = h * dpr;
            this.ctx.scale(dpr, dpr);
            this.w = w; this.h = h;
            this.cellBounds = [];
            canvas.addEventListener('mousemove', e => this._onMove(e));
            canvas.addEventListener('mouseleave', () => { this.hover = null; this._redraw(); });
        }
        _onMove(e) {
            const rect = this.canvas.getBoundingClientRect();
            const x = e.clientX - rect.left;
            const y = e.clientY - rect.top;
            let found = null;
            for (const c of this.cellBounds) {
                if (x >= c.x && x <= c.x + c.w && y >= c.y && y <= c.y + c.h) {
                    found = c; break;
                }
            }
            if (found !== this.hover) { this.hover = found; this._redraw(); }
        }
        render(preset, mat) {
            this.preset = preset;
            this.mat = mat;
            this._redraw();
        }
        _redraw() {
            const { ctx, w, h, preset, mat } = this;
            if (!preset || !mat) return;
            ctx.clearRect(0, 0, w, h);
            const n = preset.tokens.length;
            const labelW = 80, labelH = 60;
            const cellW = (w - labelW - 20) / n;
            const cellH = (h - labelH - 20) / n;
            const startX = labelW, startY = labelH;

            this.cellBounds = [];

            // Column labels (Key)
            ctx.fillStyle = '#7c3aed';
            ctx.font = 'bold 11px -apple-system, sans-serif';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'bottom';
            for (let j = 0; j < n; j++) {
                const x = startX + j * cellW + cellW / 2;
                ctx.save();
                ctx.translate(x, startY - 5);
                ctx.rotate(-Math.PI / 4);
                ctx.textAlign = 'left';
                ctx.fillText(preset.tokens[j], 0, 0);
                ctx.restore();
            }
            // Row labels (Query)
            ctx.textAlign = 'right';
            ctx.textBaseline = 'middle';
            for (let i = 0; i < n; i++) {
                const y = startY + i * cellH + cellH / 2;
                ctx.fillText(preset.tokens[i], startX - 5, y);
            }

            // Cells
            for (let i = 0; i < n; i++) {
                for (let j = 0; j < n; j++) {
                    const v = mat[i][j];
                    const x = startX + j * cellW, y = startY + i * cellH;
                    ctx.fillStyle = attentionColor(v);
                    ctx.fillRect(x, y, cellW - 1, cellH - 1);
                    if (v >= 0.15) {
                        ctx.fillStyle = v > 0.5 ? '#fff' : '#1f2937';
                        ctx.font = 'bold 10px ui-monospace, monospace';
                        ctx.textAlign = 'center';
                        ctx.textBaseline = 'middle';
                        ctx.fillText((v * 100).toFixed(0), x + cellW / 2, y + cellH / 2);
                    }
                    this.cellBounds.push({ x, y, w: cellW - 1, h: cellH - 1, i, j, v });
                }
            }

            // Hover tooltip
            if (this.hover) {
                const c = this.hover;
                ctx.strokeStyle = '#eab308';
                ctx.lineWidth = 2;
                ctx.strokeRect(c.x, c.y, c.w, c.h);
                ctx.fillStyle = '#1f2937';
                ctx.font = 'bold 12px -apple-system, sans-serif';
                ctx.textAlign = 'left';
                ctx.textBaseline = 'top';
                const tip = `${preset.tokens[c.i]} → ${preset.tokens[c.j]} : ${pctStr(c.v)}`;
                ctx.fillStyle = '#fef9e7';
                const tw = ctx.measureText(tip).width + 12;
                ctx.fillRect(5, 5, tw, 22);
                ctx.strokeStyle = '#eab308';
                ctx.strokeRect(5, 5, tw, 22);
                ctx.fillStyle = '#1f2937';
                ctx.fillText(tip, 11, 12);
            }

            // Axis labels
            ctx.fillStyle = '#9ca3af';
            ctx.font = '11px -apple-system, sans-serif';
            ctx.textAlign = 'left';
            ctx.textBaseline = 'top';
            ctx.fillText('Query (row) ↓  ×  Key (col) →', 8, h - 16);
        }
    }

    // ---------- Mini head cards ----------
    function renderHeadsGrid(preset) {
        const grid = $('heads-grid');
        grid.innerHTML = '';
        HEAD_META.forEach((meta, idx) => {
            const { mat } = buildMatrix(preset, idx);
            const card = document.createElement('div');
            card.className = 'head-card';
            if (idx === currentHead) card.classList.add('active');
            card.innerHTML = `
                <div class="head-name">${meta.name}</div>
                <div class="head-hint">${meta.hint}</div>
                <canvas></canvas>
            `;
            const cvs = card.querySelector('canvas');
            grid.appendChild(card);
            // Draw mini
            const dpr = window.devicePixelRatio || 1;
            const w = cvs.clientWidth || 180;
            const h = 100;
            cvs.width = w * dpr;
            cvs.height = h * dpr;
            const ctx = cvs.getContext('2d');
            ctx.scale(dpr, dpr);
            const n = preset.tokens.length;
            const cw = w / n, ch = h / n;
            for (let i = 0; i < n; i++) {
                for (let j = 0; j < n; j++) {
                    ctx.fillStyle = attentionColor(mat[i][j]);
                    ctx.fillRect(j * cw, i * ch, cw, ch);
                }
            }
            card.addEventListener('click', () => {
                $('cfg-head').value = String(idx);
                currentHead = idx;
                rerender();
            });
        });
    }

    // ---------- QKV trace ----------
    function renderQKVTrace(preset, mat, headIdx, selectedIdx) {
        const box = $('qkv-trace');
        if (selectedIdx === null) {
            box.innerHTML = '<div class="empty">👆 點上面任一個詞看它的完整解析</div>';
            return;
        }
        const tokens = preset.tokens;
        const row = mat[selectedIdx];
        // Sort other tokens by attention weight desc
        const rows = row
            .map((v, j) => ({ j, v, tok: tokens[j] }))
            .filter(r => r.j !== selectedIdx)
            .sort((a, b) => b.v - a.v);
        const top = rows.slice(0, 6);
        const selfWeight = row[selectedIdx];

        const html = `
            <div class="qkv-block">
                <div class="qkv-selected">
                    Query 詞：<b>「${tokens[selectedIdx]}」</b>（位置 #${selectedIdx}） · Head：<b>${HEAD_META[headIdx].name}</b>
                    <div style="margin-top:6px;font-size:.88em;color:#6b7280">
                        我這個詞現在的 <b>Q（想知道什麼）</b>去打分每個其他詞的 <b>K（我是誰）</b>，
                        然後 softmax 得到權重，最後把每個詞的 <b>V（內容）</b>照這個權重加總，
                        變成我這個詞的<b>新表徵</b>。以下是所有詞跟我的匹配分數，由高到低：
                    </div>
                </div>
                <div class="qkv-scores">
                    ${top.map(r => `
                        <div class="qkv-row ${r.v > 0.3 ? 'strong' : ''}">
                            <span class="tok">${r.tok}</span>
                            <span class="score">score</span>
                            <div class="bar" style="width:${Math.max(3, r.v * 100 * 1.5)}%"></div>
                            <span class="pct">${pctStr(r.v)}</span>
                        </div>
                    `).join('')}
                    <div class="qkv-row" style="opacity:.6">
                        <span class="tok">自己（${tokens[selectedIdx]}）</span>
                        <span class="score">self</span>
                        <div class="bar" style="width:${selfWeight * 100 * 1.5}%;background:#9ca3af"></div>
                        <span class="pct" style="color:#6b7280">${pctStr(selfWeight)}</span>
                    </div>
                </div>
            </div>
        `;
        box.innerHTML = html;
    }

    // ---------- Notes / teaching log ----------
    function renderNotes(preset) {
        const log = $('log');
        const lines = preset.noteLines || [];
        const bullets = lines.map(l => `<p>• ${l}</p>`).join('');
        log.innerHTML = `
            <h3>💡 這個句子想教你什麼</h3>
            ${bullets}
            <h3>🔑 你正在看的 Head</h3>
            <p><b>${HEAD_META[currentHead].name}</b> — ${HEAD_META[currentHead].hint}</p>
            <h3>📚 Attention 三步驟提醒</h3>
            <ul>
                <li><code>QK^T / √d_k</code> = 每個詞用自己的 Q 打分別人的 K</li>
                <li><code>softmax(scores)</code> = 分數變成 0~1 且加總 = 1 的權重</li>
                <li><code>weights · V</code> = 用權重加權其他詞的 V，得到新向量</li>
            </ul>
        `;
    }

    // ---------- Slow-motion Q·K animator ----------
    // 6 stages 標號 0-5，MVP 實作 Stage 0-1（Query 亮起 + K 逐一打分），
    // Stage 2-5 return early。舊版有 Stage 0 淡出 + Stage 1 Q 泡泡分開，
    // reviewer 建議合併成一個 stage，中間 200ms 淡出 → 之後 Q 泡泡出來，
    // 節奏更緊湊、也少一個過場。
    // Stage 0: Query 亮起（含背景淡化）
    // Stage 1: K 逐一打分（clean state machine：pendingKs / currentK / doneKs）
    // Stage 2: Softmax 尖銳化（三個 sub-phase：收攏 → 公式 → 變形）
    // 進入 stage 3 就 stop()——MVP 收尾。
    const STAGE_NAMES = [
        '1/3 Query 亮起',
        '2/3 K 逐一打分（Q·K raw scores）',
        '3/3 Softmax 尖銳化（→ 機率分布）',
    ];
    // Stage 2 從 2500 → 3500ms（Reviewer round 4 建議）：高潮期 sub-C
    // 原本 1625ms 分成三段講「強者變強、弱者被壓、Σ=1」講不完一句話。拉到 3500ms
    // 讓 sub-C 有 2275ms（1.4 倍），配旁白剛好。
    const STAGE_DURATIONS_MS = [1500, null /* per-substep */, 3500];
    const DIM_INTRO_RATIO = 0.13;

    // Easing helpers
    const easeOutBack = (t) => {
        const c1 = 1.70158, c3 = c1 + 1;
        return 1 + c3 * Math.pow(t - 1, 3) + c1 * Math.pow(t - 1, 2);
    };
    const easeInOutCubic = (t) => t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2;
    // Lerp RGB colors: `rgb(r,g,b)` 字串
    const lerpColor = (a, b, t) => {
        const r = Math.round(a[0] + (b[0] - a[0]) * t);
        const g = Math.round(a[1] + (b[1] - a[1]) * t);
        const bl = Math.round(a[2] + (b[2] - a[2]) * t);
        return `rgb(${r},${g},${bl})`;
    };

    class AttentionAnimator {
        constructor(overlayCanvas, sceneChart) {
            this.canvas = overlayCanvas;
            this.ctx = overlayCanvas.getContext('2d');
            this.scene = sceneChart;
            this.playing = false;
            this._speed = 1.0;
            this.stage = 0;
            this.stageStart = 0;
            this.elapsedInStage = 0;
            this.rafId = null;
            this.onStageChange = null;
            // Stage 1（K 打分）用的 clean state machine：
            // pendingKs = 還沒打分的 idx queue；currentK = 這輪正在打的；doneKs = 已完成的
            this.pendingKs = [];
            this.currentK = null;
            this.doneKs = [];
            this._setupHiDPI();
        }
        _setupHiDPI() {
            const dpr = window.devicePixelRatio || 1;
            const w = this.canvas.clientWidth || this.canvas.width;
            const h = this.canvas.clientHeight || this.canvas.height;
            this.canvas.width = w * dpr;
            this.canvas.height = h * dpr;
            this.ctx.setTransform(1, 0, 0, 1, 0, 0);
            this.ctx.scale(dpr, dpr);
            this.w = w; this.h = h;
        }
        // 速度即時響應：改變 speed 時同步調整 stageStart，讓當前 t 不跳
        get speed() { return this._speed; }
        set speed(v) {
            const oldSpeed = this._speed;
            const newSpeed = v || 1;
            if (oldSpeed === newSpeed) return;
            if (this.playing) {
                const now = performance.now();
                const elapsed = now - this.stageStart;
                this.stageStart = now - elapsed * (oldSpeed / newSpeed);
            } else {
                // Paused：不動 stageStart，改調整 elapsedInStage 讓 resume 時 t 值連續
                // t_before = elapsedInStage / (base/oldSpeed) = elapsed * oldSpeed / base
                // t_after 要一樣 → elapsedInStage_new = elapsedInStage * (oldSpeed/newSpeed)
                this.elapsedInStage = this.elapsedInStage * (oldSpeed / newSpeed);
            }
            this._speed = newSpeed;
        }
        // 一次算好這 row 的 raw score 用來 normalize 到 0-10 尺度
        // 觀眾看不懂 6.42 是大是小，但看得懂 8.2/10 vs 1.3/10 誰強
        _computeMaxRaw() {
            let mx = 0;
            for (let j = 0; j < this.raw.length; j++) {
                if (j === this.query) continue;
                if (this.raw[j] > mx) mx = this.raw[j];
            }
            return mx || 1;
        }
        // Stage 2 layout：按位置順序（不按分數）排 K 的 idx；算 maxSoft 給
        // softmax 長條做視覺放大（讓「尖銳化」的視覺表現最戲劇）
        _computeSoftmaxLayout() {
            this.stage2Ks = [];
            for (let j = 0; j < this.tokens.length; j++) {
                if (j !== this.query) this.stage2Ks.push(j);
            }
            let mx = 0;
            for (const j of this.stage2Ks) {
                if (this.softmaxed[j] > mx) mx = this.softmaxed[j];
            }
            this.maxSoft = mx || 1;
        }
        start(preset, headIdx, queryIdx, raw, softmaxed) {
            this.preset = preset;
            this.head = headIdx;
            this.query = queryIdx;
            this.raw = raw[queryIdx];
            this.softmaxed = softmaxed[queryIdx];
            this.tokens = preset.tokens;
            this.maxRaw = this._computeMaxRaw();
            this._computeSoftmaxLayout();
            this.stage = 0;
            this.stageStart = performance.now();
            this.pendingKs = [];
            for (let j = 0; j < this.tokens.length; j++) {
                if (j !== queryIdx) this.pendingKs.push(j);
            }
            this.currentK = null;
            this.doneKs = [];
            this.playing = true;
            this._clear();   // 清掉上一輪 finish 留下的最後一幀
            this._loop();
            if (this.onStageChange) this.onStageChange(this.stage);
        }
        pause() { this.playing = false; if (this.rafId) cancelAnimationFrame(this.rafId); }
        resume() {
            if (this.playing) return;
            this.playing = true;
            this.stageStart = performance.now() - this.elapsedInStage;
            this._loop();
        }
        stop() {
            this.playing = false;
            if (this.rafId) cancelAnimationFrame(this.rafId);
            this.stage = 0;
            this.pendingKs = [];
            this.currentK = null;
            this.doneKs = [];
            this._clear();
        }
        stepForward() {
            if (this.stage === 1) {
                // Stage 1（K 打分）內：把 currentK 塞進 doneKs、抽下一個
                if (this.currentK !== null) this.doneKs.push(this.currentK);
                if (this.pendingKs.length > 0) {
                    this.currentK = this.pendingKs.shift();
                } else {
                    this._advanceStage();
                }
            } else {
                this._advanceStage();
            }
            this.stageStart = performance.now();
            this.elapsedInStage = 0;
            // Reviewer 建議：手動 step 顯示「到達狀態」而不是「剛進入」，
            // 讓 Stage 0→1 第一個 K 不會瞬間閃過看不清
            this._draw(1);
            if (this.onStageChange) this.onStageChange(this.stage);
        }
        _advanceStage() {
            this.stage = this.stage + 1;
            // 進入 Stage 1 時初始化第一個 currentK
            if (this.stage === 1 && this.currentK === null && this.pendingKs.length > 0) {
                this.currentK = this.pendingKs.shift();
            }
            if (this.stage >= STAGE_NAMES.length) {
                // Reviewer round 4：不呼叫 stop() 因為它會 _clear()；
                // 改用 finish()：畫 Stage 2 的 t=1 結束幀 pin 在 overlay，
                // playing=false 但 canvas 保留，讓觀眾停格研究/截圖
                this.stage = STAGE_NAMES.length - 1;
                this._draw(1);
                this.stage = STAGE_NAMES.length;
                setTimeout(() => this._finish(), 0);
            }
        }
        _finish() {
            this.playing = false;
            if (this.rafId) cancelAnimationFrame(this.rafId);
            if (this.onEnd) this.onEnd();
            // 注意：不 _clear()，讓 Stage 2 最後一幀留在 overlay 上
        }
        _loop() {
            if (!this.playing) return;
            const now = performance.now();
            const elapsed = now - this.stageStart;
            this.elapsedInStage = elapsed;
            const dur = this._currentStageDurationMs();
            const t = dur === Infinity ? 1 : Math.min(1, elapsed / dur);
            this._draw(t);
            if (t >= 1 && this.stage < STAGE_NAMES.length) {
                if (this.stage === 1) {
                    // 當前 K 打分完 → 塞 doneKs、抽下一個
                    if (this.currentK !== null) this.doneKs.push(this.currentK);
                    if (this.pendingKs.length > 0) {
                        this.currentK = this.pendingKs.shift();
                        this.stageStart = now;
                    } else {
                        this.currentK = null;
                        this._advanceStage();
                        this.stageStart = now;
                        if (this.onStageChange) this.onStageChange(this.stage);
                    }
                } else {
                    this._advanceStage();
                    this.stageStart = now;
                    if (this.onStageChange) this.onStageChange(this.stage);
                }
            }
            this.rafId = requestAnimationFrame(() => this._loop());
        }
        _currentStageDurationMs() {
            const base = STAGE_DURATIONS_MS[this.stage];
            if (base === null) return 800 / this._speed;
            if (base === Infinity) return Infinity;
            return base / this._speed;
        }
        _clear() { this.ctx.clearRect(0, 0, this.w, this.h); }

        _draw(t) {
            this.ctx.clearRect(0, 0, this.w, this.h);
            if (this.stage === 0) return this._drawStage0(t);
            if (this.stage === 1) return this._drawStage1(t);
            if (this.stage === 2) return this._drawStage2(t);
            // stage >= 3 → 動畫已結束（stop() 會被觸發），不畫東西
        }

        // Stage 0（合併版）：淡出背景 + Q 泡泡出現
        // 前 13% 時間 dim 0→0.55 平滑淡出；之後 Q 泡泡 scale/alpha 彈出
        _drawStage0(t) {
            const dimT = Math.min(1, t / DIM_INTRO_RATIO);
            this._drawDimMask(dimT * 0.55);
            const qb = this.scene.tokenBounds[this.query];
            if (!qb) return;
            const bubbleT = Math.max(0, (t - DIM_INTRO_RATIO) / (1 - DIM_INTRO_RATIO));
            if (bubbleT <= 0) return;
            const qText = (this.preset.qLabels || {})[this.query] || '我這個詞想關注誰？';
            const scale = 0.5 + Math.min(1, bubbleT / 0.6) * 0.5;
            const alpha = Math.min(1, bubbleT / 0.3);
            this._drawBubble(qb.x, qb.y - 44, qText, {
                fill: '#fef3c7', stroke: '#eab308', ink: '#78350f',
                scale, alpha, prefix: 'Q：',
                fontSize: 14,   // Q 泡泡大字，跟 K 拉開層級
                padX: 10, padY: 6,
            });
        }
        // Stage 1: K 逐一打分（clean state machine：pendingKs / currentK / doneKs）
        _drawStage1(t) {
            this._drawDimMask(0.55);
            // Q 泡泡持續顯示
            const qb = this.scene.tokenBounds[this.query];
            if (qb) {
                const qText = (this.preset.qLabels || {})[this.query] || '我這個詞想關注誰？';
                this._drawBubble(qb.x, qb.y - 44, qText, {
                    fill: '#fef3c7', stroke: '#eab308', ink: '#78350f',
                    scale: 1, alpha: 1, prefix: 'Q：',
                    fontSize: 14, padX: 10, padY: 6,
                });
            }
            // 已完成的 K 用灰色細線 + 淡標籤保留
            for (const j of this.doneKs) this._drawKAndLine(j, 1, /*live=*/false);
            // 當前打分中：live
            if (this.currentK !== null) this._drawKAndLine(this.currentK, t, /*live=*/true);
        }
        _drawDimMask(alpha) {
            const { ctx } = this;
            ctx.fillStyle = `rgba(255,255,255,${alpha})`;
            ctx.fillRect(0, 0, this.w, this.h);
            const qb = this.scene.tokenBounds[this.query];
            if (!qb) return;
            ctx.save();
            ctx.globalCompositeOperation = 'destination-out';
            ctx.fillStyle = '#000';
            this._roundRect(qb.x - qb.w / 2 - 4, qb.y - 26, qb.w + 8, 52, 12);
            ctx.fill();
            ctx.restore();
        }
        _drawKAndLine(j, tLocal, live) {
            const ctx = this.ctx;
            const qb = this.scene.tokenBounds[this.query];
            const kb = this.scene.tokenBounds[j];
            if (!qb || !kb) return;
            const alpha = Math.max(0.4, tLocal);
            const kText = (this.preset.kLabels || {})[j] || this.tokens[j];
            // K 泡泡：小字、貼近節點下方（reviewer 建議：跟 Q 拉開視覺層級）
            this._drawBubble(kb.x, kb.y + 40, kText, {
                fill: live ? '#dbeafe' : '#e0e7ff',
                stroke: live ? '#3b82f6' : '#818cf8',
                ink: '#1e3a8a',
                scale: 1, alpha, prefix: 'K：',
                tailUp: true,
                fontSize: 10, padX: 6, padY: 3,
            });
            // 臨時線 query → j
            ctx.strokeStyle = live ? `rgba(124,58,237,${0.75 * tLocal})` : 'rgba(148,163,184,0.4)';
            ctx.lineWidth = live ? 2 : 1;
            ctx.setLineDash(live ? [] : [4, 3]);
            const arch = 30 + Math.abs(j - this.query) * 8;
            const cx = (qb.x + kb.x) / 2, cy = qb.y - arch;
            ctx.beginPath();
            ctx.moveTo(qb.x, qb.y - 22);
            ctx.quadraticCurveTo(cx, cy, kb.x, kb.y - 22);
            ctx.stroke();
            ctx.setLineDash([]);
            // 分數：normalize 到 0-10 尺度（reviewer 建議：raw 值觀眾沒直覺）
            const rawVal = this.raw[j];
            const normalized = (rawVal / this.maxRaw) * 10;
            const scoreStr = `Q·K = ${normalized.toFixed(1)} / 10`;
            ctx.font = 'bold 11px ui-monospace, monospace';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            const tw = ctx.measureText(scoreStr).width + 10;
            const th = 16;
            const tx = cx, ty = cy - 2;
            ctx.fillStyle = live ? 'rgba(245,243,255,0.98)' : 'rgba(243,244,246,0.9)';
            this._roundRect(tx - tw / 2, ty - th / 2, tw, th, 4);
            ctx.fill();
            ctx.strokeStyle = live ? '#a78bfa' : '#cbd5e1';
            ctx.lineWidth = 1;
            this._roundRect(tx - tw / 2, ty - th / 2, tw, th, 4);
            ctx.stroke();
            ctx.fillStyle = live ? '#7c3aed' : '#6b7280';
            ctx.fillText(scoreStr, tx, ty);
            // 迷你 bar 在標籤右邊，長度按 normalized/10 —— 觀眾一眼看強度
            const barW = 24, barH = 4;
            const bx = tx + tw / 2 + 4;
            const by = ty - barH / 2;
            ctx.fillStyle = live ? 'rgba(167,139,250,0.3)' : 'rgba(203,213,225,0.4)';
            ctx.fillRect(bx, by, barW, barH);
            ctx.fillStyle = live ? '#7c3aed' : '#94a3b8';
            ctx.fillRect(bx, by, barW * (normalized / 10), barH);
        }
        // Stage 2: Softmax 尖銳化
        // 三個 sub-phase：A 收攏 → B 公式浮出 → C 尖銳化變形
        _drawStage2(t) {
            this._drawDimMask(0.55);
            const tA = Math.min(1, t / 0.15);
            const tB = Math.min(1, Math.max(0, (t - 0.15) / 0.20));
            const tC = Math.min(1, Math.max(0, (t - 0.35) / 0.65));
            // Stage 1 UI 淡出（Q + K 泡泡 + 線）——只在 A 期間
            if (tA < 1) {
                const s1Alpha = 1 - tA;
                this.ctx.save();
                this.ctx.globalAlpha = s1Alpha;
                this._drawStage1Content();
                this.ctx.restore();
            }
            // Raw 長條淡入 + 保持
            if (tA > 0.02) this._drawRawBars(tA);
            // Formula box 浮出（B 期間 scale/alpha 動畫；之後保持）
            if (tB > 0.02) this._drawFormulaBox(tB);
            // Softmax 長條 B 期間淡入（跟 raw 一樣長），C 期間尖銳化變形
            if (tB > 0.02) this._drawSoftmaxBars(tB, tC);
            // Σ = 100% 標記在 C 後半段浮出
            if (tC > 0.7) this._drawSumBadge((tC - 0.7) / 0.3);
        }
        _drawStage1Content() {
            // Stage 1 靜態畫面（不含 dim mask），Stage 2 A phase 用來淡出
            const qb = this.scene.tokenBounds[this.query];
            if (qb) {
                const qText = (this.preset.qLabels || {})[this.query] || '我這個詞想關注誰？';
                this._drawBubble(qb.x, qb.y - 44, qText, {
                    fill: '#fef3c7', stroke: '#eab308', ink: '#78350f',
                    scale: 1, alpha: 1, prefix: 'Q：',
                    fontSize: 14, padX: 10, padY: 6,
                });
            }
            for (const j of this.doneKs) this._drawKAndLine(j, 1, false);
        }
        _stage2Layout() {
            // Round 4：token 移到 h*0.30，所以 Stage 2 從 h*0.42 開始有很多空間。
            // 三層 layout（相對比例）：
            const rawTop = this.h * 0.42;
            const rawMaxH = this.h * 0.09;   // ~30 for h=340
            const rawBase = rawTop + rawMaxH;
            const formulaY = rawBase + 8;
            const softTop = formulaY + 46;
            const softMaxH = this.h * 0.16;   // ~55 for h=340（比 raw 高，尖銳化更戲）
            const softBase = softTop + softMaxH;
            const N = this.stage2Ks.length;
            // Reviewer round 4 建議：長條 x 對齊 token x（讓「token → raw → softmax」垂直串一列）
            // Query 位置留一個「洞」有教學意義：query 不對自己打分
            const barW = this.scene.tokenBounds && this.scene.tokenBounds.length >= 2
                ? Math.max(24, (this.scene.tokenBounds[1].x - this.scene.tokenBounds[0].x) * 0.6)
                : 40;
            return { rawTop, rawMaxH, rawBase, formulaY, softTop, softMaxH, softBase, barW, N };
        }
        // 拿 token 位置陣列裡指定 idx 的 x 座標（stage2Ks[i] 的 x）
        _tokenX(j) {
            const tb = this.scene.tokenBounds && this.scene.tokenBounds[j];
            return tb ? tb.x : (this.w / 2);
        }
        _drawRawBars(alpha) {
            const ctx = this.ctx;
            const L = this._stage2Layout();
            ctx.save();
            ctx.globalAlpha = alpha;
            // 標題
            ctx.fillStyle = '#6b7280';
            ctx.font = 'bold 11px -apple-system, sans-serif';
            ctx.textAlign = 'left';
            ctx.textBaseline = 'bottom';
            ctx.fillText('Raw Q·K 分數（灰色，normalize 到 0-10）', 30, L.rawTop - 4);
            for (let i = 0; i < L.N; i++) {
                const j = this.stage2Ks[i];
                const val = this.raw[j] / this.maxRaw;
                const barH = val * L.rawMaxH;
                // Reviewer round 4：長條中心對齊 token x（每個 token 上下有自己的一列數據）
                const cx = this._tokenX(j);
                const bx = cx - L.barW / 2;
                const by = L.rawBase - barH;
                ctx.fillStyle = '#94a3b8';
                ctx.fillRect(bx, by, L.barW, barH);
                // 分數
                ctx.fillStyle = '#4b5563';
                ctx.font = 'bold 10px ui-monospace, monospace';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'bottom';
                ctx.fillText((val * 10).toFixed(1), cx, by - 1);
            }
            ctx.restore();
        }
        _drawFormulaBox(tB) {
            const ctx = this.ctx;
            const L = this._stage2Layout();
            const easedT = easeOutBack(tB);
            const scale = 0.8 + 0.2 * easedT;
            const alpha = Math.min(1, tB * 1.5);
            ctx.save();
            ctx.globalAlpha = alpha;
            const cx = this.w / 2;
            const cy = L.formulaY + 20;
            const bw = 420 * scale;
            const bh = 42 * scale;
            ctx.fillStyle = '#f5f3ff';
            ctx.strokeStyle = '#a78bfa';
            ctx.lineWidth = 2;
            this._roundRect(cx - bw / 2, cy - bh / 2, bw, bh, 8);
            ctx.fill();
            ctx.stroke();
            ctx.fillStyle = '#5b21b6';
            ctx.font = `bold ${13 * scale}px ui-monospace, monospace`;
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            ctx.fillText('softmax(x_i) = exp(x_i) / Σ exp(x_j)', cx, cy - 5 * scale);
            ctx.fillStyle = '#7c3aed';
            ctx.font = `${10 * scale}px -apple-system, sans-serif`;
            ctx.fillText('把分數變成加總為 1 的機率分佈，強者更強、弱者更弱', cx, cy + 10 * scale);
            ctx.restore();
        }
        _drawSoftmaxBars(tB, tC) {
            const ctx = this.ctx;
            const L = this._stage2Layout();
            const globalAlpha = Math.min(1, tB * 2);
            ctx.save();
            ctx.globalAlpha = globalAlpha;
            // 標題
            ctx.fillStyle = '#6d28d9';
            ctx.font = 'bold 11px -apple-system, sans-serif';
            ctx.textAlign = 'left';
            ctx.textBaseline = 'bottom';
            ctx.fillText('Softmax 後的權重（紫色，機率分布，加總 = 1）', 30, L.softTop - 4);
            const morphT = easeInOutCubic(tC);
            for (let i = 0; i < L.N; i++) {
                const j = this.stage2Ks[i];
                const rawNorm = this.raw[j] / this.maxRaw;
                const softNorm = this.softmaxed[j] / this.maxSoft;
                const currentNorm = rawNorm + (softNorm - rawNorm) * morphT;
                const barH = currentNorm * L.softMaxH;
                const cx = this._tokenX(j);
                const bx = cx - L.barW / 2;
                const by = L.softBase - barH;
                // 顏色：弱長條淡（紫淺）、強長條深（紫深）
                const softVal = this.softmaxed[j];
                const rawColor = [196, 181, 253];   // #c4b5fd
                const strongColor = [109, 40, 217]; // #6d28d9
                const strength = Math.min(1, softVal / 0.4);   // 40% 以上算強
                const barAlpha = softVal < 0.05 ? Math.max(0.3, 1 - tC * 0.7) : 1;
                ctx.save();
                ctx.globalAlpha = globalAlpha * barAlpha;
                ctx.fillStyle = lerpColor(rawColor, strongColor, strength);
                ctx.fillRect(bx, by, L.barW, barH);
                ctx.restore();
                // 分數：從 raw normalize 值 tween 到 softmax 百分比
                const rawScoreStr = (rawNorm * 10).toFixed(1);
                const softPctStr = (softVal * 100).toFixed(0) + '%';
                // 混合顯示：C 期間漸進切換
                let label;
                if (tC < 0.3) label = rawScoreStr;
                else if (tC < 0.7) label = (softVal * 100).toFixed(0) + '%';
                else label = softPctStr;
                ctx.fillStyle = softVal >= 0.30 ? '#5b21b6' : '#7c3aed';
                ctx.font = 'bold 10px ui-monospace, monospace';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'bottom';
                ctx.fillText(label, cx, by - 1);
            }
            ctx.restore();
        }
        _drawSumBadge(alpha) {
            const ctx = this.ctx;
            const L = this._stage2Layout();
            const scale = 0.5 + 0.5 * easeOutBack(alpha);
            ctx.save();
            ctx.globalAlpha = alpha;
            const cx = this.w - 90;
            const cy = L.softTop - 20;
            const bw = 100 * scale;
            const bh = 22 * scale;
            ctx.fillStyle = '#dcfce7';
            ctx.strokeStyle = '#16a34a';
            ctx.lineWidth = 2;
            this._roundRect(cx - bw / 2, cy - bh / 2, bw, bh, 5);
            ctx.fill();
            ctx.stroke();
            ctx.fillStyle = '#166534';
            ctx.font = `bold ${11 * scale}px ui-monospace, monospace`;
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            ctx.fillText('Σ = 100% ✓', cx, cy);
            ctx.restore();
        }
        _drawBubble(cx, cy, text, opts) {
            const {
                fill, stroke, ink, scale = 1, alpha = 1,
                prefix = '', tailUp = false,
                fontSize = 12, padX = 8, padY = 5,
            } = opts;
            const ctx = this.ctx;
            ctx.save();
            ctx.globalAlpha = alpha;
            ctx.font = `bold ${fontSize}px -apple-system, "Segoe UI", sans-serif`;
            const label = prefix + text;
            const tw = ctx.measureText(label).width + padX * 2;
            const th = fontSize + padY * 2;
            const w = tw * scale;
            const h = th * scale;
            const x = cx - w / 2;
            const y = cy - h / 2;
            ctx.fillStyle = fill;
            ctx.strokeStyle = stroke;
            ctx.lineWidth = 1.5;
            this._roundRect(x, y, w, h, 6);
            ctx.fill();
            ctx.stroke();
            ctx.beginPath();
            if (tailUp) {
                ctx.moveTo(cx - 5, y);
                ctx.lineTo(cx, y - 6);
                ctx.lineTo(cx + 5, y);
            } else {
                ctx.moveTo(cx - 5, y + h);
                ctx.lineTo(cx, y + h + 6);
                ctx.lineTo(cx + 5, y + h);
            }
            ctx.closePath();
            ctx.fillStyle = fill;
            ctx.fill();
            ctx.stroke();
            ctx.fillStyle = ink;
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            ctx.font = `bold ${fontSize * scale}px -apple-system, sans-serif`;
            ctx.fillText(label, cx, cy);
            ctx.restore();
        }
        _roundRect(x, y, w, h, r) {
            const ctx = this.ctx;
            ctx.beginPath();
            ctx.moveTo(x + r, y);
            ctx.arcTo(x + w, y, x + w, y + h, r);
            ctx.arcTo(x + w, y + h, x, y + h, r);
            ctx.arcTo(x, y + h, x, y, r);
            ctx.arcTo(x, y, x + w, y, r);
            ctx.closePath();
        }
    }

    // ---------- Wire up ----------
    let currentPresetIdx = 0;
    let currentHead = 0;
    let scene = null;
    let matrix = null;
    let animator = null;

    function currentPreset() { return PRESETS[currentPresetIdx]; }

    function rerender() {
        const preset = currentPreset();
        const { mat } = buildMatrix(preset, currentHead);
        scene.render(preset, mat, currentHead);
        matrix.render(preset, mat);
        renderHeadsGrid(preset);
        renderQKVTrace(preset, mat, currentHead, scene.selectedIdx);
        renderNotes(preset);
        // 動畫控制欄的狀態：只有選了詞才能按 ▶
        $('btn-play').disabled = scene.selectedIdx === null;
        if (animator) animator._clear();
        _syncAnimControls('idle');
        const st = $('anim-stage');
        if (st) st.textContent = '階段：靜態';
    }

    function _syncAnimControls(state) {
        // state: idle | playing | paused | done
        const show = (id, on) => { const el = $(id); if (el) el.hidden = !on; };
        show('btn-play', state === 'idle' || state === 'done');
        show('btn-pause', state === 'playing');
        show('btn-resume', state === 'paused');
        show('btn-step', state === 'playing' || state === 'paused');
        show('btn-replay', state === 'playing' || state === 'paused' || state === 'done');
    }

    function startAnimation() {
        const preset = currentPreset();
        const { raw, mat } = buildMatrix(preset, currentHead);
        if (scene.selectedIdx === null) return;
        animator.speed = parseFloat($('cfg-speed').value) || 1;
        animator.onStageChange = (stage) => {
            const label = STAGE_NAMES[stage] || '完成';
            $('anim-stage').textContent = '階段：' + label;
        };
        animator.onEnd = () => {
            $('anim-stage').textContent = '階段：✅ 完成（按 ↺ 重播）';
            _syncAnimControls('done');
        };
        animator.start(preset, currentHead, scene.selectedIdx, raw, mat);
        _syncAnimControls('playing');
    }

    function bootstrap() {
        const presetSel = $('cfg-preset');
        PRESETS.forEach((p, i) => {
            const opt = document.createElement('option');
            opt.value = String(i);
            opt.textContent = p.label;
            presetSel.appendChild(opt);
        });
        presetSel.addEventListener('change', () => {
            currentPresetIdx = parseInt(presetSel.value);
            scene.selectedIdx = null;
            if (animator) animator.stop();
            rerender();
        });
        $('cfg-head').addEventListener('change', () => {
            currentHead = parseInt($('cfg-head').value);
            if (animator) animator.stop();
            rerender();
        });
        $('cfg-intensity').addEventListener('input', () => {
            scene.setIntensity(parseFloat($('cfg-intensity').value));
            rerender();
        });
        // 速度即時響應（動畫中改也生效，reviewer 建議）
        $('cfg-speed').addEventListener('change', () => {
            if (animator) animator.speed = parseFloat($('cfg-speed').value) || 1;
        });

        scene = new SceneChart($('scene'));
        scene.setIntensity(1.5);
        scene.onSelect = () => {
            if (animator) animator.stop();
            rerender();
        };

        matrix = new MatrixChart($('matrix'));
        animator = new AttentionAnimator($('scene-overlay'), scene);

        // 動畫按鈕
        $('btn-play').addEventListener('click', startAnimation);
        $('btn-pause').addEventListener('click', () => { animator.pause(); _syncAnimControls('paused'); });
        $('btn-resume').addEventListener('click', () => { animator.resume(); _syncAnimControls('playing'); });
        $('btn-step').addEventListener('click', () => { animator.pause(); animator.stepForward(); _syncAnimControls('paused'); });
        $('btn-replay').addEventListener('click', () => { animator.stop(); startAnimation(); });
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape' && animator) { animator.stop(); rerender(); }
        });

        rerender();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', bootstrap);
    } else {
        bootstrap();
    }
})();
