'use strict';

(function () {

    const $ = id => document.getElementById(id);

    // ---------- Presets ----------
    // 每個 preset 一個句子 + 「signal」設定：告訴 head-builder 哪個詞應該
    // 特別關注哪個詞。剩下的隨機/位置填充。
    // signals[headIdx] = [{from, to, weight}, ...]
    //   from = query 詞 idx，to = key 詞 idx，weight = raw pre-softmax 分數
    //   高分（4-6）→ softmax 後接近 60-80% 注意力；低分（0-1）分散
    const PRESETS = [
        {
            id: 'zh-pronoun',
            label: '🇹🇼「它」到底指誰？（中文代詞解析）',
            tokens: ['我', '今天', '買了', '一本', '書', '晚上', '開始', '讀', '它'],
            noteLines: [
                '典型的中文代詞指代例句：<b>「我今天買了一本書，晚上開始讀它」</b>（原論文用的是英文 "The animal didn\'t cross the street because it was too tired"，見 en-transformer-original preset）。',
                '中間隔了 4 個詞才出現的「它」，人類一看就知道指「書」。',
                '<b>RNN</b>：訊息一步一步傳，遠距離的「書 → 它」很容易忘掉。',
                '<b>Attention</b>：「它」直接一步關注到「書」，距離不再是問題。',
                '👆 點「它」看 Head 1「代詞解析」的箭頭精準指向「書」。',
                '⚠️ 為了視覺清爽，token 陣列省略了逗號跟句號（真實 tokenizer 會保留）。',
            ],
            signals: {
                0: [   // Head 1 代詞解析: pronoun → antecedent noun
                    { from: 8, to: 4, weight: 6.0 },  // 它→書 超強
                    { from: 8, to: 7, weight: 2.5 },  // 它→讀 中
                ],
                1: [   // Head 2 主語追蹤: verb → subject
                    { from: 2, to: 0, weight: 5.0 },  // 買了→我
                    { from: 6, to: 0, weight: 3.5 },  // 開始→我
                    { from: 7, to: 0, weight: 4.5 },  // 讀→我
                ],
                2: [   // Head 3 動作對象: verb → object
                    { from: 2, to: 4, weight: 5.0 },  // 買了→書
                    { from: 7, to: 8, weight: 4.5 },  // 讀→它
                ],
                3: [   // Head 4 時間關係
                    { from: 5, to: 1, weight: 4.5 },  // 晚上→今天
                    { from: 1, to: 5, weight: 3.0 },
                ],
                4: [   // Head 5 相鄰 bigram
                    // Generated by rule (below), no explicit signals
                ],
                5: [   // Head 6 全局散播 (nothing special)
                ],
                6: [   // Head 7 修飾關係
                    { from: 3, to: 4, weight: 5.0 },  // 一本→書
                    { from: 4, to: 3, weight: 3.5 },
                ],
                7: [   // Head 8 反向照應 (書→它)
                    { from: 4, to: 8, weight: 4.5 },
                ],
            },
        },
        {
            id: 'en-pronoun',
            label: '🇺🇸 "it" refers to what? (English pronoun)',
            tokens: ['The', 'cat', 'sat', 'on', 'the', 'mat', 'because', 'it', 'was', 'tired'],
            noteLines: [
                'Classic ambiguous English: <b>"The cat sat on the mat because it was tired."</b>',
                '"it" could refer to "cat" or "mat" grammatically. Semantic clues (cats get tired, mats don\'t) point to "cat".',
                'A well-trained Transformer picks up this via <b>Head 1</b>: pronoun → antecedent with semantic match.',
                '👆 Click "it" and see the arrow point to "cat", not "mat".',
            ],
            signals: {
                0: [ { from: 7, to: 1, weight: 5.5 }, { from: 7, to: 5, weight: 1.0 } ],
                1: [ { from: 8, to: 1, weight: 5.0 }, { from: 2, to: 1, weight: 4.5 }, { from: 9, to: 1, weight: 4.0 } ],
                2: [ { from: 2, to: 5, weight: 3.5 }, { from: 3, to: 5, weight: 4.0 } ],
                3: [ { from: 6, to: 2, weight: 3.5 } ],   // because → sat
                4: [],
                5: [],
                6: [ { from: 0, to: 1, weight: 4.0 }, { from: 4, to: 5, weight: 4.0 } ],  // The→cat, the→mat
                7: [ { from: 1, to: 7, weight: 3.5 } ],   // cat ↔ it
            },
        },
        {
            id: 'zh-sentiment',
            label: '🍜「但是」翻轉情緒（餐廳評論）',
            tokens: ['這家', '餐廳', '服務', '很', '差', '但是', '菜', '真的', '好吃'],
            noteLines: [
                '評論句：<b>「這家餐廳服務很差，但是菜真的好吃」</b>',
                '模型要抓的是<b>「但是」</b>這個轉折——它切開情感兩半，讓「差」跟「好吃」不會混。',
                '<b>Head 4</b>「邏輯關係」抓「但是→差」跟「但是→好吃」都很強，這樣模型知道兩邊是對比的。',
                '<b>Head 8</b>「反向照應」讓「好吃」回頭看「菜」，「差」回頭看「服務」，情感歸屬正確。',
                '👆 點「但是」看它同時關注兩個對立情感詞。',
                '⚠️ token 陣列省略了原句的逗號（真實 tokenizer 保留）。',
            ],
            signals: {
                0: [],
                1: [ { from: 4, to: 2, weight: 4.5 }, { from: 8, to: 6, weight: 4.5 } ],   // 差→服務、好吃→菜
                2: [],
                3: [ { from: 5, to: 4, weight: 4.0 }, { from: 5, to: 8, weight: 4.0 } ],   // 但是關注兩邊
                4: [],
                5: [],
                6: [ { from: 3, to: 4, weight: 4.0 }, { from: 7, to: 8, weight: 4.0 } ],   // 很→差、真的→好吃
                7: [ { from: 8, to: 6, weight: 4.5 }, { from: 4, to: 2, weight: 4.5 } ],
            },
        },
        {
            id: 'en-transformer-original',
            label: '📄 原論文示範例句：animal / street / it 的歧義',
            tokens: ['The', 'animal', "didn't", 'cross', 'the', 'street', 'because', 'it', 'was', 'too', 'tired'],
            noteLines: [
                '<b>「Attention Is All You Need」原論文</b>展示 Transformer 注意力視覺化時用的經典句：<b>"The animal didn\'t cross the street because it was too tired."</b>',
                '"it" 語法上可以指 <b>animal</b> 或 <b>street</b>——只有語意能區分（動物會累、街道不會）。',
                'BERT / GPT 等真實模型都能學到 "it → animal"，但這個是<b>語意推理</b>不是純語法。',
                '👆 點 "it" 看 Head 1「代詞解析」正確指向 animal 而非 street。',
                '換 "tired" → "wide" 變成 "The animal didn\'t cross the street because it was too wide"，這時 it 應該指 street（街太寬）——這正是原論文 Figure 4 展示的多頭差異。',
            ],
            signals: {
                0: [   // Head 1 代詞解析
                    { from: 7, to: 1, weight: 6.0 },  // it → animal (semantic winner)
                    { from: 7, to: 5, weight: 1.5 },  // it → street (weaker, semantic loser)
                ],
                1: [   // Head 2 主語追蹤
                    { from: 8, to: 1, weight: 5.0 },  // was → animal
                    { from: 3, to: 1, weight: 4.5 },  // cross → animal
                ],
                2: [   // Head 3 動作對象
                    { from: 3, to: 5, weight: 5.0 },  // cross → street
                ],
                3: [   // Head 4 邏輯關係
                    { from: 6, to: 3, weight: 4.0 },  // because → cross
                    { from: 6, to: 9, weight: 3.5 },  // because → too
                ],
                4: [],
                5: [],
                6: [   // Head 7 修飾關係
                    { from: 0, to: 1, weight: 4.5 },  // The → animal
                    { from: 4, to: 5, weight: 4.5 },  // the → street
                    { from: 9, to: 10, weight: 4.0 }, // too → tired
                ],
                7: [   // Head 8 (待改 hint)
                    { from: 10, to: 1, weight: 3.5 },  // tired → animal (adj → noun it describes)
                ],
            },
        },
        {
            id: 'zh-longrange',
            label: '🏃 遠距離依賴（Attention 的殺手鐧）',
            tokens: ['雖然', '天氣', '很', '冷', '但是', '我', '還是', '穿', '短袖', '出門'],
            noteLines: [
                '<b>「雖然...但是...」</b>是遠距離依賴的教科書例子。中間 5-6 個詞後，「但是」還要能想起「雖然」。',
                'RNN 的記憶會被中間的詞稀釋掉。Attention 一步直達。',
                '<b>Head 1</b> 抓「但是→雖然」的邏輯配對，展現 Transformer 對長距離的優勢。',
                '同時「短袖」跟「冷」是矛盾對比，「穿→短袖」是動作對象——多個 head 同時解讀。',
                '👆 點「但是」看 Head 1 精準跨越 4 個詞指向「雖然」。',
                '⚠️ 原句「雖然天氣很冷，但是我還是穿短袖出門」有一個逗號、一個句號，token 陣列為視覺清爽省略。真實 tokenizer 會保留標點作為獨立 token。',
            ],
            signals: {
                0: [ { from: 4, to: 0, weight: 5.5 } ],   // 但是→雖然（遠距離！）
                1: [ { from: 7, to: 5, weight: 5.0 }, { from: 9, to: 5, weight: 4.0 } ],
                2: [ { from: 7, to: 8, weight: 5.0 } ],   // 穿→短袖
                3: [],
                4: [],
                5: [],
                6: [ { from: 2, to: 3, weight: 4.0 } ],  // 很→冷
                7: [ { from: 8, to: 3, weight: 3.5 } ],   // 短袖回頭看冷（矛盾對照）
            },
        },
    ];

    const HEAD_META = [
        { name: 'Head 1 · 代詞解析', hint: '代詞跳到它指的名詞', style: 'pronoun' },
        { name: 'Head 2 · 主語追蹤', hint: '動詞找回句子的主語', style: 'subject' },
        { name: 'Head 3 · 動作對象', hint: '動詞連到它作用的對象', style: 'object' },
        { name: 'Head 4 · 邏輯關係', hint: '轉折/因果/時序連詞', style: 'logic' },
        { name: 'Head 5 · 相鄰依賴', hint: '看隔壁的詞（bigram）', style: 'bigram' },
        { name: 'Head 6 · 全局散播', hint: '注意力均勻分散全句', style: 'global' },
        { name: 'Head 7 · 修飾關係', hint: '形容詞/量詞跳到被修飾的詞', style: 'modifier' },
        { name: 'Head 8 · 反向照應', hint: '罕見但真實：先行詞 / 主體回頭看指涉它的詞。BERT 雙向自注意力才有這種對稱', style: 'backref' },
    ];

    // ---------- Matrix builder ----------
    // 每個 head 用「signals + style 的基礎分佈」建 raw score，最後 row-softmax
    function buildMatrix(preset, headIdx) {
        const n = preset.tokens.length;
        const style = HEAD_META[headIdx].style;
        const raw = Array.from({ length: n }, () => new Array(n).fill(0));

        // Baseline: 每個 head 的預設分佈風格
        for (let i = 0; i < n; i++) {
            for (let j = 0; j < n; j++) {
                raw[i][j] = baselineForStyle(style, i, j, n);
            }
        }
        // 疊加 signals
        const signals = (preset.signals[headIdx] || []);
        for (const s of signals) {
            if (s.from < n && s.to < n) {
                raw[s.from][s.to] += s.weight;
            }
        }
        // Row softmax
        const mat = Array.from({ length: n }, () => new Array(n).fill(0));
        for (let i = 0; i < n; i++) {
            const rowMax = Math.max(...raw[i]);
            const exp = raw[i].map(v => Math.exp(v - rowMax));
            const sum = exp.reduce((s, v) => s + v, 0);
            for (let j = 0; j < n; j++) mat[i][j] = exp[j] / sum;
        }
        return { raw, mat };
    }

    function baselineForStyle(style, i, j, n) {
        // seeded pseudo-random so 同一 head 每次載入都一樣
        const seedNoise = ((i * 31 + j * 17 + style.length) % 100) / 100 * 0.4;
        switch (style) {
            case 'pronoun':
            case 'subject':
            case 'object':
            case 'modifier':
                // 淡淡的自關注 + 距離衰減，讓沒 signal 的 row 不至於全零
                return (i === j ? 1.5 : 0) + Math.max(0, 1.5 - Math.abs(i - j) * 0.4) + seedNoise;
            case 'logic':
                return (i === j ? 1.0 : 0) + seedNoise;
            case 'bigram':
                // 只看左右鄰居
                if (Math.abs(i - j) === 1) return 3.0 + seedNoise;
                if (i === j) return 1.5;
                return -0.5 + seedNoise;
            case 'global':
                // 均勻散播
                return 1.0 + seedNoise * 0.5;
            case 'backref':
                // 看反方向（右邊）
                if (j > i && j - i <= 3) return 2.0 + seedNoise;
                if (i === j) return 1.0;
                return seedNoise;
        }
        return seedNoise;
    }

    // ---------- Utils ----------
    function pctStr(v) { return (v * 100).toFixed(1) + '%'; }

    // 依權重取色（顏色越深表示注意力越強）
    function attentionColor(w, alpha = 1) {
        const t = Math.min(1, Math.max(0, w));
        // 白 → 紫
        const r = Math.round(255 - t * (255 - 108));
        const g = Math.round(255 - t * (255 - 40));
        const b = Math.round(255 - t * (255 - 175));
        return `rgba(${r},${g},${b},${alpha})`;
    }

    // ---------- Scene canvas: sentence + arrows ----------
    class SceneChart {
        constructor(canvas) {
            this.canvas = canvas;
            this.ctx = canvas.getContext('2d');
            this.setupHiDPI();
            this.selectedIdx = null;
            this.tokenBounds = [];
            canvas.addEventListener('click', e => this._onClick(e));
        }
        setupHiDPI() {
            const dpr = window.devicePixelRatio || 1;
            const w = this.canvas.clientWidth || this.canvas.width;
            const h = this.canvas.clientHeight || this.canvas.height;
            this.canvas.width = w * dpr;
            this.canvas.height = h * dpr;
            this.ctx.scale(dpr, dpr);
            this.w = w; this.h = h;
        }
        _onClick(e) {
            const rect = this.canvas.getBoundingClientRect();
            const x = (e.clientX - rect.left);
            const y = (e.clientY - rect.top);
            for (const t of this.tokenBounds) {
                if (x >= t.x - t.w / 2 && x <= t.x + t.w / 2 && y >= t.y - 25 && y <= t.y + 25) {
                    this.selectedIdx = t.idx;
                    if (this.onSelect) this.onSelect(t.idx);
                    return;
                }
            }
        }
        setIntensity(v) { this.intensity = v; }
        render(preset, mat, headIdx) {
            const { ctx, w, h } = this;
            ctx.clearRect(0, 0, w, h);
            const tokens = preset.tokens;
            const n = tokens.length;
            const padX = 30, padY = 60;
            const spacing = (w - padX * 2) / (n - 1 || 1);
            const y = h / 2;

            // Compute token bounds
            this.tokenBounds = tokens.map((t, i) => {
                const x = padX + i * spacing;
                ctx.font = 'bold 18px -apple-system, "Segoe UI", sans-serif';
                const tw = Math.max(46, ctx.measureText(t).width + 20);
                return { idx: i, x, y, w: tw, text: t };
            });

            // Draw arrows from selected token (before drawing tokens so tokens overlay)
            if (this.selectedIdx !== null && mat) {
                const i = this.selectedIdx;
                const row = mat[i];
                const intensity = this.intensity || 1.5;
                for (let j = 0; j < n; j++) {
                    if (j === i) continue;
                    const w0 = row[j];
                    if (w0 < 0.03) continue;   // 太細跳過
                    const from = this.tokenBounds[i];
                    const to = this.tokenBounds[j];
                    this._drawArrow(from, to, w0 * intensity, w0);
                }
            }

            // Draw tokens
            for (const tb of this.tokenBounds) {
                const isSel = tb.idx === this.selectedIdx;
                ctx.fillStyle = isSel ? '#fef3c7' : '#f3e8ff';
                ctx.strokeStyle = isSel ? '#eab308' : '#a78bfa';
                ctx.lineWidth = isSel ? 3 : 1.5;
                const rx = tb.x - tb.w / 2, ry = tb.y - 22;
                this._roundRect(rx, ry, tb.w, 44, 10);
                ctx.fill();
                ctx.stroke();
                ctx.fillStyle = '#1f2937';
                ctx.font = isSel ? 'bold 18px -apple-system, "Segoe UI", sans-serif' : '18px -apple-system, "Segoe UI", sans-serif';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'middle';
                ctx.fillText(tb.text, tb.x, tb.y);
                // idx label below
                ctx.font = '10px ui-monospace, monospace';
                ctx.fillStyle = '#9ca3af';
                ctx.fillText('#' + tb.idx, tb.x, tb.y + 30);
            }

            // Instruction
            if (this.selectedIdx === null) {
                ctx.fillStyle = '#9ca3af';
                ctx.font = '13px -apple-system, sans-serif';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'top';
                ctx.fillText('👆 點任一個詞看它的注意力扇向哪裡', w / 2, 10);
            } else {
                const t = tokens[this.selectedIdx];
                ctx.fillStyle = '#7c3aed';
                ctx.font = 'bold 13px -apple-system, sans-serif';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'top';
                ctx.fillText(`"${t}" 在 ${HEAD_META[headIdx].name} 下的注意力去向：`, w / 2, 10);
            }
        }
        _drawArrow(from, to, thickness, weight) {
            const ctx = this.ctx;
            const dir = to.x > from.x ? 1 : -1;
            const arch = 40 + Math.abs(to.idx - from.idx) * 10;
            const cx = (from.x + to.x) / 2;
            const cy = from.y - arch;
            // Curve
            ctx.strokeStyle = attentionColor(weight, 0.8);
            ctx.lineWidth = Math.max(0.6, thickness * 6);
            ctx.lineCap = 'round';
            ctx.beginPath();
            ctx.moveTo(from.x, from.y - 22);
            ctx.quadraticCurveTo(cx, cy, to.x, to.y - 22);
            ctx.stroke();
            // Arrow head
            const hx = to.x, hy = to.y - 22;
            const angle = Math.atan2(hy - cy, hx - cx);
            const ah = 8;
            ctx.fillStyle = attentionColor(weight, 0.9);
            ctx.beginPath();
            ctx.moveTo(hx, hy);
            ctx.lineTo(hx - ah * Math.cos(angle - Math.PI / 6), hy - ah * Math.sin(angle - Math.PI / 6));
            ctx.lineTo(hx - ah * Math.cos(angle + Math.PI / 6), hy - ah * Math.sin(angle + Math.PI / 6));
            ctx.closePath();
            ctx.fill();
            // Weight label near mid
            ctx.fillStyle = '#7c3aed';
            ctx.font = 'bold 10px ui-monospace, monospace';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'bottom';
            if (weight >= 0.15) ctx.fillText(pctStr(weight), cx, cy + 6);
        }
        _roundRect(x, y, w, h, r) {
            const ctx = this.ctx;
            ctx.beginPath();
            ctx.moveTo(x + r, y);
            ctx.arcTo(x + w, y, x + w, y + h, r);
            ctx.arcTo(x + w, y + h, x, y + h, r);
            ctx.arcTo(x, y + h, x, y, r);
            ctx.arcTo(x, y, x + w, y, r);
            ctx.closePath();
        }
    }

    // ---------- Matrix heatmap canvas ----------
    class MatrixChart {
        constructor(canvas) {
            this.canvas = canvas;
            this.ctx = canvas.getContext('2d');
            const dpr = window.devicePixelRatio || 1;
            const w = canvas.clientWidth || canvas.width;
            const h = canvas.clientHeight || canvas.height;
            canvas.width = w * dpr;
            canvas.height = h * dpr;
            this.ctx.scale(dpr, dpr);
            this.w = w; this.h = h;
            this.cellBounds = [];
            canvas.addEventListener('mousemove', e => this._onMove(e));
            canvas.addEventListener('mouseleave', () => { this.hover = null; this._redraw(); });
        }
        _onMove(e) {
            const rect = this.canvas.getBoundingClientRect();
            const x = e.clientX - rect.left;
            const y = e.clientY - rect.top;
            let found = null;
            for (const c of this.cellBounds) {
                if (x >= c.x && x <= c.x + c.w && y >= c.y && y <= c.y + c.h) {
                    found = c; break;
                }
            }
            if (found !== this.hover) { this.hover = found; this._redraw(); }
        }
        render(preset, mat) {
            this.preset = preset;
            this.mat = mat;
            this._redraw();
        }
        _redraw() {
            const { ctx, w, h, preset, mat } = this;
            if (!preset || !mat) return;
            ctx.clearRect(0, 0, w, h);
            const n = preset.tokens.length;
            const labelW = 80, labelH = 60;
            const cellW = (w - labelW - 20) / n;
            const cellH = (h - labelH - 20) / n;
            const startX = labelW, startY = labelH;

            this.cellBounds = [];

            // Column labels (Key)
            ctx.fillStyle = '#7c3aed';
            ctx.font = 'bold 11px -apple-system, sans-serif';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'bottom';
            for (let j = 0; j < n; j++) {
                const x = startX + j * cellW + cellW / 2;
                ctx.save();
                ctx.translate(x, startY - 5);
                ctx.rotate(-Math.PI / 4);
                ctx.textAlign = 'left';
                ctx.fillText(preset.tokens[j], 0, 0);
                ctx.restore();
            }
            // Row labels (Query)
            ctx.textAlign = 'right';
            ctx.textBaseline = 'middle';
            for (let i = 0; i < n; i++) {
                const y = startY + i * cellH + cellH / 2;
                ctx.fillText(preset.tokens[i], startX - 5, y);
            }

            // Cells
            for (let i = 0; i < n; i++) {
                for (let j = 0; j < n; j++) {
                    const v = mat[i][j];
                    const x = startX + j * cellW, y = startY + i * cellH;
                    ctx.fillStyle = attentionColor(v);
                    ctx.fillRect(x, y, cellW - 1, cellH - 1);
                    if (v >= 0.15) {
                        ctx.fillStyle = v > 0.5 ? '#fff' : '#1f2937';
                        ctx.font = 'bold 10px ui-monospace, monospace';
                        ctx.textAlign = 'center';
                        ctx.textBaseline = 'middle';
                        ctx.fillText((v * 100).toFixed(0), x + cellW / 2, y + cellH / 2);
                    }
                    this.cellBounds.push({ x, y, w: cellW - 1, h: cellH - 1, i, j, v });
                }
            }

            // Hover tooltip
            if (this.hover) {
                const c = this.hover;
                ctx.strokeStyle = '#eab308';
                ctx.lineWidth = 2;
                ctx.strokeRect(c.x, c.y, c.w, c.h);
                ctx.fillStyle = '#1f2937';
                ctx.font = 'bold 12px -apple-system, sans-serif';
                ctx.textAlign = 'left';
                ctx.textBaseline = 'top';
                const tip = `${preset.tokens[c.i]} → ${preset.tokens[c.j]} : ${pctStr(c.v)}`;
                ctx.fillStyle = '#fef9e7';
                const tw = ctx.measureText(tip).width + 12;
                ctx.fillRect(5, 5, tw, 22);
                ctx.strokeStyle = '#eab308';
                ctx.strokeRect(5, 5, tw, 22);
                ctx.fillStyle = '#1f2937';
                ctx.fillText(tip, 11, 12);
            }

            // Axis labels
            ctx.fillStyle = '#9ca3af';
            ctx.font = '11px -apple-system, sans-serif';
            ctx.textAlign = 'left';
            ctx.textBaseline = 'top';
            ctx.fillText('Query (row) ↓  ×  Key (col) →', 8, h - 16);
        }
    }

    // ---------- Mini head cards ----------
    function renderHeadsGrid(preset) {
        const grid = $('heads-grid');
        grid.innerHTML = '';
        HEAD_META.forEach((meta, idx) => {
            const { mat } = buildMatrix(preset, idx);
            const card = document.createElement('div');
            card.className = 'head-card';
            if (idx === currentHead) card.classList.add('active');
            card.innerHTML = `
                <div class="head-name">${meta.name}</div>
                <div class="head-hint">${meta.hint}</div>
                <canvas></canvas>
            `;
            const cvs = card.querySelector('canvas');
            grid.appendChild(card);
            // Draw mini
            const dpr = window.devicePixelRatio || 1;
            const w = cvs.clientWidth || 180;
            const h = 100;
            cvs.width = w * dpr;
            cvs.height = h * dpr;
            const ctx = cvs.getContext('2d');
            ctx.scale(dpr, dpr);
            const n = preset.tokens.length;
            const cw = w / n, ch = h / n;
            for (let i = 0; i < n; i++) {
                for (let j = 0; j < n; j++) {
                    ctx.fillStyle = attentionColor(mat[i][j]);
                    ctx.fillRect(j * cw, i * ch, cw, ch);
                }
            }
            card.addEventListener('click', () => {
                $('cfg-head').value = String(idx);
                currentHead = idx;
                rerender();
            });
        });
    }

    // ---------- QKV trace ----------
    function renderQKVTrace(preset, mat, headIdx, selectedIdx) {
        const box = $('qkv-trace');
        if (selectedIdx === null) {
            box.innerHTML = '<div class="empty">👆 點上面任一個詞看它的完整解析</div>';
            return;
        }
        const tokens = preset.tokens;
        const row = mat[selectedIdx];
        // Sort other tokens by attention weight desc
        const rows = row
            .map((v, j) => ({ j, v, tok: tokens[j] }))
            .filter(r => r.j !== selectedIdx)
            .sort((a, b) => b.v - a.v);
        const top = rows.slice(0, 6);
        const selfWeight = row[selectedIdx];

        const html = `
            <div class="qkv-block">
                <div class="qkv-selected">
                    Query 詞：<b>「${tokens[selectedIdx]}」</b>（位置 #${selectedIdx}） · Head：<b>${HEAD_META[headIdx].name}</b>
                    <div style="margin-top:6px;font-size:.88em;color:#6b7280">
                        我這個詞現在的 <b>Q（想知道什麼）</b>去打分每個其他詞的 <b>K（我是誰）</b>，
                        然後 softmax 得到權重，最後把每個詞的 <b>V（內容）</b>照這個權重加總，
                        變成我這個詞的<b>新表徵</b>。以下是所有詞跟我的匹配分數，由高到低：
                    </div>
                </div>
                <div class="qkv-scores">
                    ${top.map(r => `
                        <div class="qkv-row ${r.v > 0.3 ? 'strong' : ''}">
                            <span class="tok">${r.tok}</span>
                            <span class="score">score</span>
                            <div class="bar" style="width:${Math.max(3, r.v * 100 * 1.5)}%"></div>
                            <span class="pct">${pctStr(r.v)}</span>
                        </div>
                    `).join('')}
                    <div class="qkv-row" style="opacity:.6">
                        <span class="tok">自己（${tokens[selectedIdx]}）</span>
                        <span class="score">self</span>
                        <div class="bar" style="width:${selfWeight * 100 * 1.5}%;background:#9ca3af"></div>
                        <span class="pct" style="color:#6b7280">${pctStr(selfWeight)}</span>
                    </div>
                </div>
            </div>
        `;
        box.innerHTML = html;
    }

    // ---------- Notes / teaching log ----------
    function renderNotes(preset) {
        const log = $('log');
        const lines = preset.noteLines || [];
        const bullets = lines.map(l => `<p>• ${l}</p>`).join('');
        log.innerHTML = `
            <h3>💡 這個句子想教你什麼</h3>
            ${bullets}
            <h3>🔑 你正在看的 Head</h3>
            <p><b>${HEAD_META[currentHead].name}</b> — ${HEAD_META[currentHead].hint}</p>
            <h3>📚 Attention 三步驟提醒</h3>
            <ul>
                <li><code>QK^T / √d_k</code> = 每個詞用自己的 Q 打分別人的 K</li>
                <li><code>softmax(scores)</code> = 分數變成 0~1 且加總 = 1 的權重</li>
                <li><code>weights · V</code> = 用權重加權其他詞的 V，得到新向量</li>
            </ul>
        `;
    }

    // ---------- Wire up ----------
    let currentPresetIdx = 0;
    let currentHead = 0;
    let scene = null;
    let matrix = null;

    function currentPreset() { return PRESETS[currentPresetIdx]; }

    function rerender() {
        const preset = currentPreset();
        const { mat } = buildMatrix(preset, currentHead);
        scene.render(preset, mat, currentHead);
        matrix.render(preset, mat);
        renderHeadsGrid(preset);
        renderQKVTrace(preset, mat, currentHead, scene.selectedIdx);
        renderNotes(preset);
    }

    function bootstrap() {
        // Fill preset dropdown
        const presetSel = $('cfg-preset');
        PRESETS.forEach((p, i) => {
            const opt = document.createElement('option');
            opt.value = String(i);
            opt.textContent = p.label;
            presetSel.appendChild(opt);
        });
        presetSel.addEventListener('change', () => {
            currentPresetIdx = parseInt(presetSel.value);
            scene.selectedIdx = null;
            rerender();
        });
        $('cfg-head').addEventListener('change', () => {
            currentHead = parseInt($('cfg-head').value);
            rerender();
        });
        $('cfg-intensity').addEventListener('input', () => {
            scene.setIntensity(parseFloat($('cfg-intensity').value));
            rerender();
        });

        scene = new SceneChart($('scene'));
        scene.setIntensity(1.5);
        scene.onSelect = () => rerender();

        matrix = new MatrixChart($('matrix'));

        rerender();
    }

    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', bootstrap);
    } else {
        bootstrap();
    }
})();
